# Simple workflow for deploying static content to GitHub Pages
name: Build packages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout packages
        uses: actions/checkout@v4
      - name: Checkout Neverball
        uses: actions/checkout@v4
        with:
          repository: Neverball/neverball
          path: neverball
      - name: Install ffmpeg
        run: sudo apt-get install -y ffmpeg
      - name: Build base SOLs
        run: "(cd neverball && make -j2 sols)"
      - name: Build packages
        run: "(cd neverball && make -f mk/packages.mk -j2 PACKAGES_DIR=$(pwd)/../ OUTPUT_DIR=$(pwd)/../build/)"
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          # Upload entire repository
          path: 'build'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
